import { z } from "zod";

/**
 * All ids are UUIDs generated by Postgres (gen_random_uuid()). Kept as plain
 * strings rather than branded types to avoid friction at the API boundary;
 * correctness is enforced by foreign keys in the database, not the type system.
 */
export const IdSchema = z.string().uuid();
export type Id = z.infer<typeof IdSchema>;
